// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardBookingsController from "./card_bookings_controller"
application.register("card-bookings", CardBookingsController)

import CardEventsController from "./card_events_controller"
application.register("card-events", CardEventsController)

import EventRouteController from "./event_route_controller"
application.register("event-route", EventRouteController)

import FlashesController from "./flashes_controller"
application.register("flashes", FlashesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
