// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardsController from "./cards_controller"
application.register("cards", CardsController)

import EventRouteController from "./event_route_controller"
application.register("event-route", EventRouteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ToggleInputController from "./toggle_input_controller"
application.register("toggle-input", ToggleInputController)
